version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
       #- ls -la /root/.m2/repository/
       - ls -ltr otpslara-parent/
  #    - cd otpslara
  #    - mvn clean compile test
  #    - pwd
  #    - ls -ltr target/maven-status/
  #    - ls -ltr target/generated-sources
  #    - ls -ltr target/classes
  build:
    commands:
      #- mvn package
      - cd otpslara-parent
      - mvn clean install compile package -X
  post_build:
    commands:
      #- echo "Build Succesfull."
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  files:
    - 'appspec.yml'
    - 'template.yml'
    - 'scripts/*'
    - 'target/ROOT.war'
    - 'template-configuration.json'
